/**
 * Creating a sidebar enables you to:
 - Create an ordered group of docs
 - Render a sidebar from the docs folder structure
 - Include docs from different sources

- E.g. tour guides, api docs, etc.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{
    type: 'autogenerated',
    dirName: '.'
  }],
  */

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'intro-physical-ai',
        'hardware-requirements'
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module1-ros2/overview',
        'module1-ros2/nodes-topics-services',
        'module1-ros2/python-ros-integration',
        'module1-ros2/urdf-humanoids',
        'module1-ros2/exercises'
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module2-digital-twin/overview',
        'module2-digital-twin/gazebo-setup',
        'module2-digital-twin/physics-simulation',
        'module2-digital-twin/unity-integration',
        'module2-digital-twin/sensor-simulation',
        'module2-digital-twin/exercises'
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module3-ai-brain/overview',
        'module3-ai-brain/isaac-sim',
        'module3-ai-brain/isaac-ros',
        'module3-ai-brain/nav2-path-planning',
        'module3-ai-brain/exercises'
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module4-vla/overview',
        'module4-vla/voice-to-action',
        'module4-vla/cognitive-planning',
        'module4-vla/capstone-project',
        'module4-vla/exercises'
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Weekly Breakdown',
      items: [
        'weekly/weeks1-2-intro-physical-ai',
        'weekly/weeks3-5-ros2',
        'weekly/weeks6-7-gazebo',
        'weekly/weeks8-10-isaac',
        'weekly/weeks11-12-humanoid',
        'weekly/week13-conversational-robotics'
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Supporting Materials',
      items: [
        'support/learning-outcomes',
        'support/assessments',
        'support/troubleshooting',
        'support/best-practices'
      ],
      collapsed: true,
    }
  ],
};

module.exports = sidebars;
